#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

PREV_V=$(cd release/app && npm pkg get version | sed 's/"//g')

exec < /dev/tty

node "$(dirname -- "$0")"/bump-version.js

NEW_V=$(cd release/app && npm pkg get version | sed 's/"//g')

if [ $PREV_V == $NEW_V ]
then
  printf "\nNothing was bumped!"
else
  printf "\nBumping tag...\n"
  git tag -a v$NEW_V -m "chore: bump package version to $NEW_V"
  printf "\nPushing...\n"
  git push --atomic origin main v$NEW_V
  printf "\nDone!"
fi
