#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

PREV_V=$(cd release/app && npm pkg get version | sed 's/"//g')

exec < /dev/tty

node "$(dirname -- "$0")"/bump-version.js

NEW_V=$(cd release/app && npm pkg get version | sed 's/"//g')

if [ $PREV_V == $NEW_V ]
then
  printf "\nNothing was bumped!"
else
  printf "\nDisabling post-commit before commiting.."
  chmod -x .husky/post-commit
  printf "\nCommiting.."
  git commit -m "chore: bump package version to $NEW_V"
  printf "\nEnabling post-commit.."
  chmod +x .husky/post-commit
  printf "\nBumping tag..."
  git tag v$NEW_V
  printf "\nPushing.."
  git push && git push --tags
  printf "Done!"
fi
